addressbook/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup', views.signup, name="signup"),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('',include('app.urls')),
]

app/urls.py
from django.urls import path
from app import views
from django.urls import include, re_path

app_name = "app"

urlpatterns = [
    path('', views.index, name="index"),
    path('home', views.home, name="home"),
    path('customers', views.employees, name="employees"),
    path('search_employees', views.search_employees, name='search_employees'),
    path('Delete/<int:id>', views.delrec, name = "delete_customer"),
]

app/models.py
from django.db import models
import uuid
# Create your models here.


class Employee(models.Model):

    first_name = models.CharField(max_length = 1000)
    last_name = models.CharField(max_length = 1000)
    cust_id = models.EmailField(max_length=70,blank=True, null= True, unique= True)
    age = models.IntegerField()
    sex = models.CharField(max_length = 100)
    address = models.CharField(max_length = 1000)
    contactno = models.CharField(max_length = 1000)

    def __str__(self):
        return self.first_name

class Blog(models.Model):
    name = models.CharField(max_length = 1000)
    author = models.CharField(max_length = 1000)
    price = models.CharField(max_length = 1000)

    def __str__(self):
        return self.name

app/forms.py
from django import forms
from app.models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

app/views.py
from queue import Empty
from xml.dom.minidom import Identified
from django.shortcuts import render, redirect
from numpy import require
from app.models import Employee, Blog
from app.forms import BlogForm
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.db import connection
import subprocess, shlex
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages

# Create your views here.


def index(request):
    return render(request, "app/index.html")

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, "User Created Successfully! You can login now!.")
            return redirect('app:index')
    else:
        form = UserCreationForm()

    return render(request, "registration/signup.html", {"form":form})

@login_required
def home(request):
    return render(request, "app/home.html")

@login_required
def employees(request):
    if request.method == "POST":
        id = request.POST.get("id")
        cust_id = request.POST.get("cust_id")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        age = request.POST.get("age")
        sex = request.POST.get("sex")
        address = request.POST.get("address")
        contactno = request.POST.get("contactno")

        # Saving to DB using Django ORM - the best way
        Employee.objects.create(first_name=first_name, last_name=last_name, cust_id=cust_id,
        age=age, sex=sex, address=address, contactno=contactno)

        # # Direct SQL Queries - the wrong way
        # cursor = connection.cursor()
        # query = "INSERT INTO app_employee (cust_id, first_name, last_name, age, sex, address, contactno) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s')" % (cust_id, first_name, last_name, age, sex, address, contactno)
        # cursor.execute(query)

        # # Direct SQL Queries - the correct way
        # cursor = connection.cursor()
        # cursor.execute("INSERT INTO app_employee (cust_id, first_name, last_name, age, sex, address, contactno) VALUES (%s, %s, %s, %s, %s, %s, %s)", [cust_id, first_name, last_name, age, sex, address, contactno])

        return redirect("app:employees")
    else:
        # Fetch all employees using Django ORM
        employees = Employee.objects.all()

        return render(request, 'app/customers.html',
        {"employees":employees})

def delrec(request,id):
    delemployee = Employee.objects.filter(id=id)
    delemployee.delete()
    result = Employee.objects.all()
    #return render(request, 'app/customers.html',{"employees":result})
    return redirect("app:employees")


@login_required
@csrf_exempt
def search_employees(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        search_term = request.POST.get('searchTerm')

        # Searching employees using Django ORM - the best way
        employees = Employee.objects.filter(first_name__icontains=search_term)

        # # Searching employees using raw() - the wrong way
        # query = "SELECT * FROM app_employee WHERE first_name ILIKE '%s';" % search_term
        # employees = Employee.objects.raw(query)

        # # Searching employees using raw() - the correct way
        # employees = Employee.objects.raw('SELECT * FROM app_employee WHERE first_name ILIKE %s;',[search_term])

        # # Searching employees using extra() - the wrong way
        # employees = Employee.objects.extra(where=["first_name ILIKE '%s'" % search_term])

        # # Searching employees using extra() - the correct way
        # employees = Employee.objects.extra(where=['first_name ILIKE %s'], params=[search_term])

        html = render_to_string('app/search_customers.html',
        {'employees':employees})

        return HttpResponse(html)

app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 5 -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
    crossorigin="anonymous">

    <!-- Fontawesome -->
    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">

    <!-- Google Fonts - Nunito -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito" rel="stylesheet">

    <!-- Data Tables -->
    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">

    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/select/1.3.3/css/select.bootstrap5.min.css">

    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <style type="text/css">
      body { background: lightgrey !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
   </style>

    <style>
      /* To remove the down arrow by the right of the user avatar in the navbar */
      .dropdown-toggle::after {
        content: none;
      }
    </style>

    {% block head %}

    {% endblock %}
  </head>
  <body>
    <!-- Bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous">
    </script>

    <!-- jQuery for Data Tables -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous">
    </script>

    <!-- JS for Data Tables -->
    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js">
    </script>

    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'app:home' %}">Address Book</a>
        <button class="navbar-toggler" type="button"
        data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false"
        aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page"
              href="{% url 'app:employees' %}">Customer Details</a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
              aria-ex
              panded="true">
                <div class="white-color hover-orange size-24px">
                  <span>{{ user }}</span>
                  <i class="fas fa-user"></i>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-end">
                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block body %}

    {% endblock %}

  </body>
</html>

app/templates/app/customers.html
{% extends "app/base.html" %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 class="mt-4 text-center">Customer Details</h3>

  <div class="row mb-2">
    <div class="col-md-6">
      <div style="width:50%;" class="input-group">
        <input id="searchBox" type="text" class="form-control"
        placeholder="Search Details">
        <button class="btn btn-outline-secondary" type="button" id="searchEmployee">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>

    <div class="col-md-6">
      <div class="float-end">
        {% if request.user.is_superuser %}
        <button type="button" class="btn btn-success" data-bs-toggle="modal"
        data-bs-target="#addEmployeeModal">
          <i class="fas fa-plus"></i>
          Add
        </button>
        {% else %}

        {% endif %}
      </div>
    </div>
  </div>

  <div id="searchOutput">
    <table id="employeeTable" class="table table-bordered table-hover table-grey">
      <thead class="table-dark">
        <tr>
          <th>ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email ID</th>
          <th>Age</th>
          <th>Sex</th>
          <th>Address</th>
          <th>Contact No.</th>
          {% if request.user.is_superuser %}
          <th>Actions</th>
          {% else %}

          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
        <tr>
          <td>{{ employee.id }}</td>
          <td>{{ employee.first_name }}</td>
          <td>{{ employee.last_name }}</td>
          <td>{{ employee.cust_id }}</td>
          <td>{{ employee.age }}</td>
          <td>{{ employee.sex }}</td>
          <td>{{ employee.address }}</td>
          <td>{{ employee.contactno }}</td>
          
          {% if request.user.is_superuser %}

          <td><a href ="/Delete/{{ employee.id }} " button class="btn btn-danger">Delete</a></td>
        </tr>
        {% else %}

        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  


  <!-- Add Employee Modal -->
  <div class="modal fade" id="addEmployeeModal" tabindex="-1" aria-labelledby="addEmployeeModalLable"
   aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Add Customer Details</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"
          aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-4">
              <input style="width:100%;" name="first_name" type="text"
              class="form-control mb-2" placeholder="First Name" required>

              <input styl e="width:100%;" name="last_name" type="text"
              class="form-control mb-2" placeholder="Last Name" required>

              <input style="width:100%;" name="cust_id" type="text"
              class="form-control mb-2" placeholder="Email ID" required>

              <input style="width:100%;" name="age" type="text"
              class="form-control mb-2" placeholder="Age" required>

              <input style="width:100%;" name="sex" type="text"
              class="form-control mb-2" placeholder="Sex" required>

              <input style="width:100%;" name="address" type="text"
              class="form-control mb-2" placeholder="Address" required>

              <input style="width:100%;" name="contactno" type="text"
              class="form-control" placeholder="Contact No." required>
            </div>

            <button class="btn btn-success" type="submit" name="button">Save</button>
            <button type="button" class="btn btn-warning" data-bs-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>

<!-- JS Function to Search Employee -->
<script type="text/javascript">
  $(document).ready(function() {
    $(document).on("click","#searchEmployee",function() {
      var searchTerm = $("#searchBox").val();

      $.ajax({
          type: "POST",
          url: "{% url 'app:search_employees' %}",
          data: {'searchTerm':searchTerm},
          success: function(response){
            $('#searchOutput').html(response);
          }
      });

    });
  });
</script>

{% endblock %}

app/templates/app/delete.html
{%  extends 'app/base.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'app:delete_customer' item.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'home' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

app/templates/app/home.html
{% extends "app/base.html" %}

{% block head %}

<title>Home</title>


{% endblock %}

{% block body %}

    
    <div class="card-body text-center">
      <h1>Welcome to Address Book!</h1>
    </div>
{% endblock %}

app/templates/app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 5 -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
    crossorigin="anonymous">

    <!-- Fontawesome -->
    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">

    <!-- Google Fonts - Nunito -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito" rel="stylesheet">

    <!-- Data Tables -->
    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">

    <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/select/1.3.3/css/select.bootstrap5.min.css">

    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <style>
      /* To remove the down arrow by the right of the user avatar in the navbar */
      .dropdown-toggle::after {
        content: none;
      }
    </style>

  </head>
  <body>
    <!-- Bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous">
    </script>

    <!-- jQuery for Data Tables -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous">
    </script>

    <!-- JS for Data Tables -->
    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js">
    </script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand mx-auto" href="{% url 'app:index' %}">Address Book</a>

      </div>
    </nav>

    <div class="container">
      <div class="mt-2">
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"
            aria-label="Close"></button>
          </div>
          {% endfor %}
        {% endif %}
      </div>
      <div class="card mt-4">
        <div class="card-body text-center">
          <h1>Welcome to Address Book!</h1>
          <a class="btn btn-warning" href="{% url 'signup' %}">Sign Up</a>
          <a class="btn btn-success" href="{% url 'login' %}">Log In</a>
        </div>
      </div>
    </div>

  </body>
</html>

app/templates/app/search_customers.html
<table id="employeeTable" class="table table-warning">
  <thead class="table-secondary">
    <tr>
    <th>ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email ID</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Address</th>
    <th>Contact No.</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
    <tr>
      <td>{{ employee.id }}</td>
      <td>{{ employee.first_name }}</td>
      <td>{{ employee.last_name }}</td>
      <td>{{ employee.cust_id }}</td>
      <td>{{ employee.age }}</td>
      <td>{{ employee.sex }}</td>
      <td>{{ employee.address }}</td>
      <td>{{ employee.contactno }}</td>
    </tr>
      
    {% endfor %}
  </tbody>
</table>

templates/bs5_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group mt-3">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}
  </div>
{% endfor %}